[2023-08-18T19:39:49.015+0000] {processor.py:156} INFO - Started process (PID=34) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:39:49.020+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:39:49.022+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:39:49.022+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:39:49.759+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:39:49.756+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:39:49.760+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:39:49.776+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.769 seconds
[2023-08-18T19:40:20.239+0000] {processor.py:156} INFO - Started process (PID=62) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:40:20.243+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:40:20.245+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:40:20.245+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:40:20.411+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:40:20.410+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:40:20.412+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:40:20.426+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.197 seconds
[2023-08-18T19:40:50.732+0000] {processor.py:156} INFO - Started process (PID=90) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:40:50.735+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:40:50.737+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:40:50.736+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:40:50.875+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:40:50.873+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:40:50.876+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:40:50.890+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.166 seconds
[2023-08-18T19:41:21.057+0000] {processor.py:156} INFO - Started process (PID=118) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:41:21.059+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:41:21.060+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:41:21.060+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:41:21.213+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:41:21.212+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:41:21.214+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:41:21.228+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.175 seconds
[2023-08-18T19:41:51.534+0000] {processor.py:156} INFO - Started process (PID=146) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:41:51.536+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:41:51.537+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:41:51.537+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:41:51.679+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:41:51.678+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:41:51.680+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:41:51.696+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.168 seconds
[2023-08-18T19:42:21.845+0000] {processor.py:156} INFO - Started process (PID=165) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:42:21.849+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:42:21.851+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:42:21.850+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:42:22.006+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:42:22.005+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:42:22.007+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:42:22.022+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.183 seconds
[2023-08-18T19:42:52.238+0000] {processor.py:156} INFO - Started process (PID=194) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:42:52.241+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:42:52.242+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:42:52.242+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:42:52.368+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:42:52.366+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:42:52.368+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:42:52.383+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.149 seconds
[2023-08-18T19:43:22.570+0000] {processor.py:156} INFO - Started process (PID=222) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:43:22.574+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:43:22.576+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:43:22.576+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:43:22.718+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:43:22.717+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:43:22.719+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:43:22.735+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.171 seconds
[2023-08-18T19:43:52.938+0000] {processor.py:156} INFO - Started process (PID=251) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:43:52.940+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:43:52.941+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:43:52.941+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:43:53.074+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:43:53.073+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:43:53.075+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:43:53.089+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.158 seconds
[2023-08-18T19:44:23.466+0000] {processor.py:156} INFO - Started process (PID=278) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:44:23.469+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:44:23.470+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:44:23.470+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:44:23.601+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:44:23.600+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:44:23.602+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:44:23.616+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.156 seconds
[2023-08-18T19:44:53.764+0000] {processor.py:156} INFO - Started process (PID=306) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:44:53.768+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:44:53.769+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:44:53.769+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:44:53.895+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:44:53.894+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:44:53.896+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:44:53.909+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.151 seconds
[2023-08-18T19:45:24.189+0000] {processor.py:156} INFO - Started process (PID=334) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:45:24.191+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:45:24.192+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:45:24.192+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:45:24.350+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:45:24.348+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:45:24.351+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:45:24.367+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.180 seconds
[2023-08-18T19:45:54.593+0000] {processor.py:156} INFO - Started process (PID=353) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:45:54.597+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:45:54.599+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:45:54.599+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:45:54.735+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:45:54.734+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:45:54.736+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:45:54.750+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.164 seconds
[2023-08-18T19:46:25.186+0000] {processor.py:156} INFO - Started process (PID=380) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:46:25.189+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:46:25.190+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:46:25.190+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:46:25.330+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:46:25.329+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:46:25.331+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:46:25.345+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.164 seconds
[2023-08-18T19:51:33.399+0000] {processor.py:156} INFO - Started process (PID=34) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:51:33.403+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:51:33.406+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:51:33.405+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:51:34.093+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:51:34.089+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:51:34.094+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:51:34.115+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.734 seconds
[2023-08-18T19:52:04.613+0000] {processor.py:156} INFO - Started process (PID=63) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:52:04.615+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:52:04.617+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:52:04.616+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:52:04.793+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:52:04.791+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:52:04.794+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:52:04.810+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.202 seconds
[2023-08-18T19:52:34.998+0000] {processor.py:156} INFO - Started process (PID=90) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:52:35.000+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:52:35.002+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:52:35.002+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:52:35.138+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:52:35.137+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:52:35.139+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:52:35.153+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.163 seconds
[2023-08-18T19:53:05.476+0000] {processor.py:156} INFO - Started process (PID=119) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:53:05.478+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:53:05.479+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:53:05.479+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:53:05.637+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:53:05.635+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:53:05.637+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:53:05.653+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.180 seconds
[2023-08-18T19:53:35.836+0000] {processor.py:156} INFO - Started process (PID=147) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:53:35.838+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:53:35.839+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:53:35.839+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:53:35.962+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:53:35.961+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:53:35.963+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:53:35.976+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.143 seconds
[2023-08-18T19:54:06.285+0000] {processor.py:156} INFO - Started process (PID=166) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:54:06.287+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:54:06.288+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:54:06.288+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:54:06.459+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:54:06.454+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:54:06.460+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:54:06.479+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.199 seconds
[2023-08-18T19:54:36.634+0000] {processor.py:156} INFO - Started process (PID=196) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:54:36.637+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:54:36.638+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:54:36.638+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:54:36.782+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:54:36.780+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:54:36.783+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:54:36.800+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.172 seconds
[2023-08-18T19:55:07.163+0000] {processor.py:156} INFO - Started process (PID=223) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:55:07.165+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:55:07.166+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:55:07.165+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:55:07.327+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:55:07.325+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:55:07.328+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:55:07.346+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.187 seconds
[2023-08-18T19:55:37.529+0000] {processor.py:156} INFO - Started process (PID=251) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:55:37.531+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:55:37.533+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:55:37.533+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:55:37.708+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:55:37.706+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:55:37.708+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:55:37.724+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.203 seconds
[2023-08-18T19:56:07.985+0000] {processor.py:156} INFO - Started process (PID=279) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:56:07.987+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:56:07.989+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:56:07.988+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:56:08.141+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:56:08.139+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:56:08.142+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:56:08.156+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.177 seconds
[2023-08-18T19:56:33.299+0000] {processor.py:156} INFO - Started process (PID=298) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:56:33.303+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:56:33.305+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:56:33.305+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:56:33.464+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:56:33.462+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:56:33.464+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:56:33.478+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.187 seconds
[2023-08-18T19:57:03.814+0000] {processor.py:156} INFO - Started process (PID=326) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:57:03.815+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:57:03.819+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:57:03.818+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:57:03.987+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:57:03.985+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:57:03.988+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:57:04.003+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.195 seconds
[2023-08-18T19:57:34.263+0000] {processor.py:156} INFO - Started process (PID=355) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:57:34.267+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:57:34.268+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:57:34.268+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:57:34.399+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:57:34.398+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:57:34.400+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:57:34.414+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.158 seconds
[2023-08-18T19:58:04.747+0000] {processor.py:156} INFO - Started process (PID=382) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:58:04.749+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:58:04.751+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:58:04.751+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:58:04.925+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:58:04.924+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:58:04.926+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:58:04.942+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.205 seconds
[2023-08-18T19:58:35.087+0000] {processor.py:156} INFO - Started process (PID=411) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:58:35.089+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:58:35.090+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:58:35.090+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:58:35.265+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:58:35.263+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:58:35.266+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:58:35.281+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.199 seconds
[2023-08-18T19:59:05.476+0000] {processor.py:156} INFO - Started process (PID=431) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:59:05.479+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:59:05.481+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:59:05.481+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:59:05.618+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:59:05.617+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:59:05.619+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:59:05.637+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.168 seconds
[2023-08-18T19:59:35.950+0000] {processor.py:156} INFO - Started process (PID=459) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:59:35.952+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T19:59:35.954+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:59:35.954+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:59:36.131+0000] {logging_mixin.py:117} INFO - [2023-08-18T19:59:36.130+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T19:59:36.132+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T19:59:36.147+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.204 seconds
[2023-08-18T20:00:06.283+0000] {processor.py:156} INFO - Started process (PID=487) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:00:06.287+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:00:06.288+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:00:06.288+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:00:06.412+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:00:06.411+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:00:06.414+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:00:06.430+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.152 seconds
[2023-08-18T20:00:36.803+0000] {processor.py:156} INFO - Started process (PID=515) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:00:36.805+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:00:36.807+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:00:36.807+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:00:37.005+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:00:37.003+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:00:37.006+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:00:37.025+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.229 seconds
[2023-08-18T20:01:07.241+0000] {processor.py:156} INFO - Started process (PID=542) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:01:07.244+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:01:07.247+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:01:07.247+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:01:07.434+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:01:07.432+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:01:07.435+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:01:07.450+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.217 seconds
[2023-08-18T20:01:37.719+0000] {processor.py:156} INFO - Started process (PID=570) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:01:37.723+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:01:37.724+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:01:37.724+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:01:37.848+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:01:37.846+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:01:37.848+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:01:37.862+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.147 seconds
[2023-08-18T20:02:08.043+0000] {processor.py:156} INFO - Started process (PID=597) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:02:08.046+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:02:08.048+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:02:08.048+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:02:08.212+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:02:08.211+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:02:08.213+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:02:08.229+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.189 seconds
[2023-08-18T20:02:38.575+0000] {processor.py:156} INFO - Started process (PID=616) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:02:38.576+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:02:38.577+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:02:38.577+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:02:38.689+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:02:38.688+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:02:38.690+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:02:38.704+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.131 seconds
[2023-08-18T20:03:08.897+0000] {processor.py:156} INFO - Started process (PID=644) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:03:08.899+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:03:08.900+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:03:08.900+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:03:09.068+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:03:09.066+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:03:09.069+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:03:09.086+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.193 seconds
[2023-08-18T20:03:39.238+0000] {processor.py:156} INFO - Started process (PID=672) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:03:39.241+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:03:39.243+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:03:39.243+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:03:39.392+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:03:39.389+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:03:39.392+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:03:39.416+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.184 seconds
[2023-08-18T20:04:09.739+0000] {processor.py:156} INFO - Started process (PID=700) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:04:09.740+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:04:09.741+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:04:09.741+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:04:09.865+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:04:09.864+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:04:09.866+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:04:09.880+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.146 seconds
[2023-08-18T20:04:40.082+0000] {processor.py:156} INFO - Started process (PID=729) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:04:40.084+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:04:40.087+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:04:40.086+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:04:40.251+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:04:40.250+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:04:40.252+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:04:40.268+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.191 seconds
[2023-08-18T20:05:10.518+0000] {processor.py:156} INFO - Started process (PID=756) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:05:10.521+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:05:10.523+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:05:10.522+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:05:10.650+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:05:10.649+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:05:10.651+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:05:10.665+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.151 seconds
[2023-08-18T20:05:40.895+0000] {processor.py:156} INFO - Started process (PID=783) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:05:40.897+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:05:40.898+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:05:40.898+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:05:41.046+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:05:41.044+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:05:41.047+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:05:41.062+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.171 seconds
[2023-08-18T20:06:11.310+0000] {processor.py:156} INFO - Started process (PID=801) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:06:11.312+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:06:11.313+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:06:11.313+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:06:11.436+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:06:11.435+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:06:11.437+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:06:11.450+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.143 seconds
[2023-08-18T20:06:41.756+0000] {processor.py:156} INFO - Started process (PID=829) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:06:41.760+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:06:41.761+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:06:41.761+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:06:41.919+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:06:41.917+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:06:41.919+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:06:41.934+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.183 seconds
[2023-08-18T20:07:12.069+0000] {processor.py:156} INFO - Started process (PID=858) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:12.071+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:07:12.072+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:07:12.072+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:12.208+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:07:12.207+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 132, in <module>
    "months": months
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/baseoperator.py", line 408, in apply_defaults
    result = func(self, **kwargs, default_args=default_args)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/python.py", line 162, in __init__
    raise AirflowException('`python_callable` param must be callable')
airflow.exceptions.AirflowException: `python_callable` param must be callable
[2023-08-18T20:07:12.209+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:12.224+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.159 seconds
[2023-08-18T20:07:25.423+0000] {processor.py:156} INFO - Started process (PID=867) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:25.425+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:07:25.426+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:07:25.426+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:25.569+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:07:25.568+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 173, in <module>
    download_raw_data_task >> create_dataproc_cluster_task >> transformations >> delete_dataproc_cluster_task
NameError: name 'download_raw_data_task' is not defined
[2023-08-18T20:07:25.570+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:25.589+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.170 seconds
[2023-08-18T20:07:55.859+0000] {processor.py:156} INFO - Started process (PID=894) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:55.863+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:07:55.864+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:07:55.864+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:56.022+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:07:56.021+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 173, in <module>
    download_raw_data_task >> create_dataproc_cluster_task >> transformations >> delete_dataproc_cluster_task
NameError: name 'download_raw_data_task' is not defined
[2023-08-18T20:07:56.022+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:07:56.049+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.196 seconds
[2023-08-18T20:08:26.248+0000] {processor.py:156} INFO - Started process (PID=923) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:26.254+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:08:26.255+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:26.255+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:26.469+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:26.467+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 173, in <module>
    download_raw_data_task >> create_dataproc_cluster_task >> transformations >> delete_dataproc_cluster_task
NameError: name 'download_raw_data_task' is not defined
[2023-08-18T20:08:26.469+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:26.492+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.251 seconds
[2023-08-18T20:08:27.390+0000] {processor.py:156} INFO - Started process (PID=924) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:27.391+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:08:27.393+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:27.392+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:27.542+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:27.657+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:27.657+0000] {manager.py:507} INFO - Created Permission View: can delete on DAG:tbf_analysis_dag
[2023-08-18T20:08:27.664+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:27.664+0000] {manager.py:507} INFO - Created Permission View: can read on DAG:tbf_analysis_dag
[2023-08-18T20:08:27.667+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:27.667+0000] {manager.py:507} INFO - Created Permission View: can edit on DAG:tbf_analysis_dag
[2023-08-18T20:08:27.668+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:27.668+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:08:27.678+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:27.677+0000] {dag.py:2594} INFO - Creating ORM DAG for tbf_analysis_dag
[2023-08-18T20:08:27.686+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:27.686+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to 2023-08-18T00:00:00+00:00, run_after=2023-08-18T00:00:00+00:00
[2023-08-18T20:08:27.701+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.316 seconds
[2023-08-18T20:08:28.565+0000] {processor.py:156} INFO - Started process (PID=925) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:28.568+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:08:28.569+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:28.569+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:28.730+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:28.741+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:28.741+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:08:28.754+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:28.754+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to 2023-08-18T00:00:00+00:00, run_after=2023-08-18T00:00:00+00:00
[2023-08-18T20:08:28.767+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.209 seconds
[2023-08-18T20:08:59.023+0000] {processor.py:156} INFO - Started process (PID=957) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:59.025+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:08:59.026+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:59.026+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:59.203+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:08:59.224+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:59.224+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:08:59.240+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:08:59.240+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:08:59.251+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.231 seconds
[2023-08-18T20:09:29.282+0000] {processor.py:156} INFO - Started process (PID=983) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:09:29.283+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:09:29.283+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:09:29.283+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:09:29.395+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:09:29.414+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:09:29.414+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:09:29.427+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:09:29.427+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:09:29.439+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.159 seconds
[2023-08-18T20:09:59.648+0000] {processor.py:156} INFO - Started process (PID=1010) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:09:59.649+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:09:59.650+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:09:59.650+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:09:59.787+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:09:59.807+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:09:59.807+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:09:59.823+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:09:59.823+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:09:59.834+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.189 seconds
[2023-08-18T20:10:29.953+0000] {processor.py:156} INFO - Started process (PID=1039) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:10:29.955+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:10:29.956+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:10:29.956+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:10:30.122+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:10:30.146+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:10:30.146+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:10:30.167+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:10:30.167+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:10:30.182+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.234 seconds
[2023-08-18T20:11:00.392+0000] {processor.py:156} INFO - Started process (PID=1067) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:11:00.396+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:11:00.400+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:11:00.398+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:11:00.665+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:11:00.692+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:11:00.691+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:11:00.709+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:11:00.709+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:11:00.724+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.347 seconds
[2023-08-18T20:11:30.963+0000] {processor.py:156} INFO - Started process (PID=1086) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:11:30.965+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:11:30.967+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:11:30.967+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:11:31.091+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:11:31.110+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:11:31.110+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:11:31.124+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:11:31.124+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:11:31.135+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.176 seconds
[2023-08-18T20:12:01.234+0000] {processor.py:156} INFO - Started process (PID=1115) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:12:01.236+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:12:01.237+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:12:01.237+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:12:01.375+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:12:01.394+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:12:01.394+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:12:01.408+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:12:01.408+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:12:01.419+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.191 seconds
[2023-08-18T20:12:31.597+0000] {processor.py:156} INFO - Started process (PID=1143) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:12:31.598+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:12:31.599+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:12:31.599+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:12:31.733+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:12:31.754+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:12:31.754+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:12:31.769+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:12:31.769+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:12:31.781+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.186 seconds
[2023-08-18T20:13:02.055+0000] {processor.py:156} INFO - Started process (PID=1172) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:13:02.057+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:13:02.058+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:13:02.058+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:13:02.223+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:13:02.245+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:13:02.244+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:13:02.261+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:13:02.261+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:13:02.273+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.221 seconds
[2023-08-18T20:13:32.438+0000] {processor.py:156} INFO - Started process (PID=1200) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:13:32.441+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:13:32.442+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:13:32.442+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:13:32.625+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:13:32.647+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:13:32.647+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:13:32.663+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:13:32.663+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:13:32.674+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.241 seconds
[2023-08-18T20:14:02.770+0000] {processor.py:156} INFO - Started process (PID=1227) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:14:02.771+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:14:02.773+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:14:02.773+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:14:02.910+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:14:02.930+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:14:02.930+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:14:02.945+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:14:02.945+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:14:02.956+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.190 seconds
[2023-08-18T20:14:33.166+0000] {processor.py:156} INFO - Started process (PID=1253) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:14:33.168+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:14:33.169+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:14:33.169+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:14:33.377+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:14:33.404+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:14:33.404+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:14:33.424+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:14:33.423+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:14:33.438+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.283 seconds
[2023-08-18T20:15:03.808+0000] {processor.py:156} INFO - Started process (PID=1273) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:03.812+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:15:03.814+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:03.814+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:03.969+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:03.991+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:03.991+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:15:04.007+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:04.007+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:15:04.018+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.218 seconds
[2023-08-18T20:15:34.091+0000] {processor.py:156} INFO - Started process (PID=1299) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:34.094+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:15:34.095+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:34.095+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:34.221+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:34.242+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:34.241+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:15:34.256+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:34.256+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:15:34.268+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.181 seconds
[2023-08-18T20:15:47.204+0000] {processor.py:156} INFO - Started process (PID=1309) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:47.207+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:15:47.208+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:47.208+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:47.351+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:47.392+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:47.392+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:15:47.405+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:47.405+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:15:47.418+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.218 seconds
[2023-08-18T20:15:48.405+0000] {processor.py:156} INFO - Started process (PID=1319) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:48.406+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:15:48.406+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:48.406+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:48.530+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:15:48.541+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:48.541+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:15:48.555+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:15:48.555+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:15:48.568+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.166 seconds
[2023-08-18T20:16:18.870+0000] {processor.py:156} INFO - Started process (PID=1338) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:16:18.873+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:16:18.875+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:16:18.875+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:16:19.048+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:16:19.070+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:16:19.070+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:16:19.087+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:16:19.087+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:16:19.098+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.234 seconds
[2023-08-18T20:16:49.341+0000] {processor.py:156} INFO - Started process (PID=1366) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:16:49.343+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:16:49.344+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:16:49.344+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:16:49.490+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:16:49.513+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:16:49.513+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:16:49.538+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:16:49.538+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:16:49.551+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.215 seconds
[2023-08-18T20:17:19.810+0000] {processor.py:156} INFO - Started process (PID=1394) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:17:19.814+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:17:19.816+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:17:19.816+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:17:19.997+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:17:20.020+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:17:20.019+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:17:20.035+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:17:20.035+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:17:20.046+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.245 seconds
[2023-08-18T20:17:50.269+0000] {processor.py:156} INFO - Started process (PID=1422) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:17:50.272+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:17:50.273+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:17:50.273+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:17:50.411+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:17:50.432+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:17:50.432+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:17:50.446+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:17:50.446+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:17:50.457+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.193 seconds
[2023-08-18T20:18:20.747+0000] {processor.py:156} INFO - Started process (PID=1450) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:18:20.750+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:18:20.752+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:18:20.752+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:18:20.910+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:18:20.932+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:18:20.931+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:18:20.950+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:18:20.950+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:18:20.973+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.234 seconds
[2023-08-18T20:18:51.152+0000] {processor.py:156} INFO - Started process (PID=1478) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:18:51.154+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:18:51.155+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:18:51.155+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:18:51.304+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:18:51.325+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:18:51.325+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:18:51.343+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:18:51.343+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:18:51.358+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.210 seconds
[2023-08-18T20:19:21.690+0000] {processor.py:156} INFO - Started process (PID=1507) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:19:21.691+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:19:21.692+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:19:21.692+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:19:21.813+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:19:21.831+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:19:21.831+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:19:21.845+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:19:21.845+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:19:21.856+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.170 seconds
[2023-08-18T20:19:52.074+0000] {processor.py:156} INFO - Started process (PID=1526) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:19:52.076+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:19:52.080+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:19:52.080+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:19:52.234+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:19:52.255+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:19:52.255+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:19:52.271+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:19:52.271+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:19:52.283+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.216 seconds
[2023-08-18T20:20:22.447+0000] {processor.py:156} INFO - Started process (PID=1553) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:20:22.450+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:20:22.452+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:20:22.452+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:20:22.583+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:20:22.603+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:20:22.603+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:20:22.618+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:20:22.618+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:20:22.628+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.189 seconds
[2023-08-18T20:20:52.880+0000] {processor.py:156} INFO - Started process (PID=1580) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:20:52.882+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:20:52.883+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:20:52.883+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:20:53.046+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:20:53.067+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:20:53.067+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:20:53.083+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:20:53.083+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:20:53.094+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.218 seconds
[2023-08-18T20:21:10.103+0000] {processor.py:156} INFO - Started process (PID=1599) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:21:10.105+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:21:10.107+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:21:10.107+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:21:10.258+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:21:10.257+0000] {dagbag.py:330} ERROR - Failed to import: /opt/airflow/dags/tbf_analysis_dag.py
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/dagbag.py", line 326, in parse
    loader.exec_module(new_module)
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/airflow/dags/tbf_analysis_dag.py", line 40, in <module>
    extract_script_loc = os.environ.get("DAGS_LOCATION")+"01_ExtractData_LoadToGCS.sh"
TypeError: unsupported operand type(s) for +: 'NoneType' and 'str'
[2023-08-18T20:21:10.259+0000] {processor.py:770} WARNING - No viable dags retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:21:10.274+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.175 seconds
[2023-08-18T20:25:05.233+0000] {processor.py:156} INFO - Started process (PID=33) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:25:05.235+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:25:05.236+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:25:05.236+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:25:06.001+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:25:06.070+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:25:06.070+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:25:06.099+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:25:06.099+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:25:06.117+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.889 seconds
[2023-08-18T20:25:36.569+0000] {processor.py:156} INFO - Started process (PID=62) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:25:36.574+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:25:36.575+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:25:36.575+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:25:36.740+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:25:36.763+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:25:36.763+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:25:36.779+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:25:36.779+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:25:36.791+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.239 seconds
[2023-08-18T20:26:06.871+0000] {processor.py:156} INFO - Started process (PID=91) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:06.872+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:26:06.873+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:06.873+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:07.050+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:07.072+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:07.072+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:26:07.089+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:07.089+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:26:07.102+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.236 seconds
[2023-08-18T20:26:37.294+0000] {processor.py:156} INFO - Started process (PID=119) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:37.295+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:26:37.296+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:37.296+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:37.479+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:37.500+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:37.500+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:26:37.516+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:37.516+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:26:37.526+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.237 seconds
[2023-08-18T20:26:47.478+0000] {processor.py:156} INFO - Started process (PID=129) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:47.479+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:26:47.479+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:47.479+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:47.599+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:26:47.700+0000] {processor.py:727} INFO - Executed failure callback for <TaskInstance: tbf_analysis_dag.download_raw_data_task scheduled__2023-08-18T00:00:00+00:00 [up_for_retry]> in state up_for_retry
[2023-08-18T20:26:47.708+0000] {processor.py:727} INFO - Executed failure callback for <TaskInstance: tbf_analysis_dag.download_raw_data_task manual__2023-08-18T20:08:41.331719+00:00 [up_for_retry]> in state up_for_retry
[2023-08-18T20:26:47.714+0000] {processor.py:727} INFO - Executed failure callback for <TaskInstance: tbf_analysis_dag.download_raw_data_task scheduled__2023-08-18T00:00:00+00:00 [failed]> in state failed
[2023-08-18T20:26:47.726+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:47.726+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:26:47.738+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:26:47.738+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:26:47.748+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.272 seconds
[2023-08-18T20:27:17.890+0000] {processor.py:156} INFO - Started process (PID=148) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:27:17.893+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:27:17.894+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:27:17.894+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:27:18.067+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:27:18.200+0000] {processor.py:727} INFO - Executed failure callback for <TaskInstance: tbf_analysis_dag.download_raw_data_task manual__2023-08-18T20:08:41.331719+00:00 [failed]> in state failed
[2023-08-18T20:27:18.216+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:27:18.216+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:27:18.229+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:27:18.229+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:27:18.238+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.356 seconds
[2023-08-18T20:27:48.380+0000] {processor.py:156} INFO - Started process (PID=176) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:27:48.382+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:27:48.384+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:27:48.384+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:27:48.531+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:27:48.551+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:27:48.551+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:27:48.566+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:27:48.566+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:27:48.577+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.202 seconds
[2023-08-18T20:29:44.509+0000] {processor.py:156} INFO - Started process (PID=34) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:29:44.515+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:29:44.524+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:29:44.523+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:29:45.205+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:29:45.247+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:29:45.246+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:29:45.262+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:29:45.262+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:29:45.274+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.768 seconds
[2023-08-18T20:30:15.750+0000] {processor.py:156} INFO - Started process (PID=61) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:30:15.753+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:30:15.755+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:30:15.755+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:30:15.911+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:30:15.933+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:30:15.933+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:30:15.957+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:30:15.957+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:30:15.970+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.228 seconds
[2023-08-18T20:30:46.134+0000] {processor.py:156} INFO - Started process (PID=90) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:30:46.135+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:30:46.136+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:30:46.136+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:30:46.247+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:30:46.265+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:30:46.265+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:30:46.279+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:30:46.279+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:30:46.290+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.159 seconds
[2023-08-18T20:31:16.555+0000] {processor.py:156} INFO - Started process (PID=119) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:31:16.557+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:31:16.558+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:31:16.558+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:31:16.705+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:31:16.726+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:31:16.725+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:31:16.740+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:31:16.740+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:31:16.751+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.200 seconds
[2023-08-18T20:31:46.863+0000] {processor.py:156} INFO - Started process (PID=148) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:31:46.864+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:31:46.865+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:31:46.865+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:31:47.029+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:31:47.053+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:31:47.053+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:31:47.069+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:31:47.069+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:31:47.082+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.228 seconds
[2023-08-18T20:32:17.490+0000] {processor.py:156} INFO - Started process (PID=168) to work on /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:32:17.491+0000] {processor.py:758} INFO - Processing file /opt/airflow/dags/tbf_analysis_dag.py for tasks to queue
[2023-08-18T20:32:17.493+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:32:17.492+0000] {dagbag.py:525} INFO - Filling up the DagBag from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:32:17.651+0000] {processor.py:768} INFO - DAG(s) dict_keys(['tbf_analysis_dag']) retrieved from /opt/airflow/dags/tbf_analysis_dag.py
[2023-08-18T20:32:17.673+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:32:17.673+0000] {dag.py:2573} INFO - Sync 1 DAGs
[2023-08-18T20:32:17.689+0000] {logging_mixin.py:117} INFO - [2023-08-18T20:32:17.688+0000] {dag.py:3328} INFO - Setting next_dagrun for tbf_analysis_dag to None, run_after=None
[2023-08-18T20:32:17.699+0000] {processor.py:178} INFO - Processing /opt/airflow/dags/tbf_analysis_dag.py took 0.213 seconds
