[2023-08-28T06:29:15.491+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-28T06:29:15.501+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tbf_analysis_dag_v21.authenticate_service_acct_task scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-28T06:29:15.507+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tbf_analysis_dag_v21.authenticate_service_acct_task scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-28T06:29:15.507+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-28T06:29:15.515+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): authenticate_service_acct_task> on 2023-08-28 00:00:00+00:00
[2023-08-28T06:29:15.523+0000] {standard_task_runner.py:57} INFO - Started process 116 to run task
[2023-08-28T06:29:15.529+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tbf_analysis_dag_v21', 'authenticate_service_acct_task', 'scheduled__2023-08-28T00:00:00+00:00', '--job-id', '43', '--raw', '--subdir', 'DAGS_FOLDER/tbf_analysis_dag_v21.py', '--cfg-path', '/tmp/tmpfbi4vc3p']
[2023-08-28T06:29:15.534+0000] {standard_task_runner.py:85} INFO - Job 43: Subtask authenticate_service_acct_task
[2023-08-28T06:29:15.555+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-28T06:29:15.602+0000] {task_command.py:415} INFO - Running <TaskInstance: tbf_analysis_dag_v21.authenticate_service_acct_task scheduled__2023-08-28T00:00:00+00:00 [running]> on host 98d871aa1e03
[2023-08-28T06:29:15.615+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-28T06:29:15.673+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tbf_analysis_dag_v21' AIRFLOW_CTX_TASK_ID='authenticate_service_acct_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-28T00:00:00+00:00'
[2023-08-28T06:29:15.676+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-28T06:29:15.677+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo starting_gcloud_auth; gcloud auth activate-service-account terraform@trans-border-freights-394419.iam.gserviceaccount.com --key-file /.google/credentials/google_credentials.json; echo ending_gcloud_auth']
[2023-08-28T06:29:15.691+0000] {subprocess.py:86} INFO - Output:
[2023-08-28T06:29:15.695+0000] {subprocess.py:93} INFO - starting_gcloud_auth
[2023-08-28T06:29:16.441+0000] {subprocess.py:93} INFO - Activated service account credentials for: [terraform@trans-border-freights-394419.iam.gserviceaccount.com]
[2023-08-28T06:29:17.018+0000] {subprocess.py:93} INFO - ending_gcloud_auth
[2023-08-28T06:29:17.019+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-08-28T06:29:17.044+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=tbf_analysis_dag_v21, task_id=authenticate_service_acct_task, execution_date=20230828T000000, start_date=20230828T062915, end_date=20230828T062917
[2023-08-28T06:29:17.079+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-08-28T06:29:17.100+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
