[2023-08-28T05:42:38.360+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-28T05:42:38.367+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: tbf_analysis_dag_v20.install_pip_package_task scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-28T05:42:38.372+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: tbf_analysis_dag_v20.install_pip_package_task scheduled__2023-08-28T00:00:00+00:00 [queued]>
[2023-08-28T05:42:38.372+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2023-08-28T05:42:38.379+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): install_pip_package_task> on 2023-08-28 00:00:00+00:00
[2023-08-28T05:42:38.383+0000] {standard_task_runner.py:57} INFO - Started process 110 to run task
[2023-08-28T05:42:38.387+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'tbf_analysis_dag_v20', 'install_pip_package_task', 'scheduled__2023-08-28T00:00:00+00:00', '--job-id', '34', '--raw', '--subdir', 'DAGS_FOLDER/tbf_analysis_dag_v20.py', '--cfg-path', '/tmp/tmpbg1p_1yu']
[2023-08-28T05:42:38.389+0000] {standard_task_runner.py:85} INFO - Job 34: Subtask install_pip_package_task
[2023-08-28T05:42:38.402+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:195: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  SQL_ALCHEMY_CONN = conf.get("database", "SQL_ALCHEMY_CONN")

[2023-08-28T05:42:38.431+0000] {task_command.py:415} INFO - Running <TaskInstance: tbf_analysis_dag_v20.install_pip_package_task scheduled__2023-08-28T00:00:00+00:00 [running]> on host 7d623e02890b
[2023-08-28T05:42:38.441+0000] {warnings.py:109} WARNING - /home/***/.local/lib/python3.8/site-packages/***/utils/sqlalchemy.py:124: DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
  return not conf.get("database", "sql_alchemy_conn").startswith("mssql")

[2023-08-28T05:42:38.485+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='tbf_analysis_dag_v20' AIRFLOW_CTX_TASK_ID='install_pip_package_task' AIRFLOW_CTX_EXECUTION_DATE='2023-08-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-08-28T00:00:00+00:00'
[2023-08-28T05:42:38.486+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-08-28T05:42:38.487+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', "gcloud compute ssh trans-border-freights-394419-dataproc-m --zone=us-central1-b --project=trans-border-freights-394419 --command='pip install xlrd'"]
[2023-08-28T05:42:38.497+0000] {subprocess.py:86} INFO - Output:
[2023-08-28T05:42:39.152+0000] {subprocess.py:93} INFO - WARNING: The private SSH key file for gcloud does not exist.
[2023-08-28T05:42:39.154+0000] {subprocess.py:93} INFO - WARNING: The public SSH key file for gcloud does not exist.
[2023-08-28T05:42:39.154+0000] {subprocess.py:93} INFO - WARNING: You do not have an SSH key for gcloud.
[2023-08-28T05:42:39.155+0000] {subprocess.py:93} INFO - WARNING: SSH keygen will be executed to generate a key.
[2023-08-28T05:42:39.156+0000] {subprocess.py:93} INFO - This tool needs to create the directory [/home/***/.ssh] before
[2023-08-28T05:42:39.156+0000] {subprocess.py:93} INFO - being able to generate SSH keys.
[2023-08-28T05:42:39.157+0000] {subprocess.py:93} INFO - 
[2023-08-28T05:42:39.243+0000] {subprocess.py:93} INFO - Do you want to continue (Y/n)?  Generating public/private rsa key pair.
[2023-08-28T05:42:39.245+0000] {subprocess.py:93} INFO - /home/***/.ssh/google_compute_engine already exists.
[2023-08-28T05:42:39.249+0000] {subprocess.py:93} INFO - Overwrite (y/n)?
[2023-08-28T05:42:39.249+0000] {subprocess.py:93} INFO - ERROR: (gcloud.compute.ssh) [/usr/bin/ssh-keygen] exited with return code [1].
[2023-08-28T05:42:39.342+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2023-08-28T05:42:39.353+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2023-08-28T05:42:39.356+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=tbf_analysis_dag_v20, task_id=install_pip_package_task, execution_date=20230828T000000, start_date=20230828T054238, end_date=20230828T054239
[2023-08-28T05:42:39.364+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 34 for task install_pip_package_task (Bash command failed. The command returned a non-zero exit code 1.; 110)
[2023-08-28T05:42:39.422+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-08-28T05:42:39.438+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
